#define DIS                 (4.0)
#define ENEMY_NUMBER        (7)
#define HEADER_LINES        (3)
#define IMAGE_HEIGHT        (160)
#define IMAGE_WIDTH         (120)
#define PI2                 (2.0 * M_PI)
#define MAX_FILENAME_LENGTH (255)
#define MAX_X               (30)
#define MAX_Y               (30)
#define MAX_Z               (30)
#define MIN_X               (-30)
#define MIN_Y               (-30)
#define MIN_Z               (-30)
#define TRINUM              (100000)
#define MISSILE_NUMBER      (5)
#define MYDUR               (5)
#define popXsize            (400)
#define popYsize            (80)
#define TEKIDUR             (30)
#define TexNum              (2)
#define WINDOW_HEIGHT       (800)
#define WINDOW_WIDTH        (1200)
#define XRATE               (WINDOW_WIDTH / (MAX_X - MIN_X))
